/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nanda
 */
public class klikPencari extends javax.swing.JFrame {

    /**
     * Creates new form klikPencari
     */
    public klikPencari() {
        initComponents();
        Balikpapan.setVisible(false);
        Bandar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        close = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        ketikcari = new javax.swing.JTextField();
        test = new javax.swing.JButton();
        test2 = new javax.swing.JButton();
        Balikpapan = new javax.swing.JComboBox<>();
        Bandar = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, 30));

        close.setContentAreaFilled(false);
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 30, 20));

        cari.setContentAreaFilled(false);
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 60, 20));

        ketikcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketikcariActionPerformed(evt);
            }
        });
        getContentPane().add(ketikcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 180, 20));

        test.setBorderPainted(false);
        test.setContentAreaFilled(false);
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });
        getContentPane().add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 80, 30));

        test2.setBorderPainted(false);
        test2.setContentAreaFilled(false);
        test2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test2ActionPerformed(evt);
            }
        });
        getContentPane().add(test2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 80, 30));

        Balikpapan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Balikpapan", "Kebonsari", "Sumbersari", "Botolinggo" }));
        Balikpapan.setBorder(null);
        Balikpapan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BalikpapanMouseClicked(evt);
            }
        });
        Balikpapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalikpapanActionPerformed(evt);
            }
        });
        getContentPane().add(Balikpapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 150, 290, 28));

        Bandar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bandar Lampung", "Item 2", "Item 3", "Item 4" }));
        Bandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandarActionPerformed(evt);
            }
        });
        getContentPane().add(Bandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 180, 290, 28));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pencarian berdasar kota.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 820, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ketikcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketikcariActionPerformed
    
    }//GEN-LAST:event_ketikcariActionPerformed

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
    Balikpapan.setVisible(true);
    Bandar.setVisible(false);
    }//GEN-LAST:event_testActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    new login().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
    new pencarian().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_cariActionPerformed

    private void BalikpapanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BalikpapanMouseClicked
    
    }//GEN-LAST:event_BalikpapanMouseClicked

    private void BalikpapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalikpapanActionPerformed
    new pencarian().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_BalikpapanActionPerformed

    private void BandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandarActionPerformed
    new pencarian().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_BandarActionPerformed

    private void test2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test2ActionPerformed
    Bandar.setVisible(true);
    Balikpapan.setVisible(false);
    
    }//GEN-LAST:event_test2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(klikPencari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(klikPencari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(klikPencari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(klikPencari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new klikPencari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Balikpapan;
    private javax.swing.JComboBox<String> Bandar;
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton cari;
    private javax.swing.JButton close;
    private javax.swing.JTextField ketikcari;
    private javax.swing.JButton test;
    private javax.swing.JButton test2;
    // End of variables declaration//GEN-END:variables
}
