/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nanda
 */
public class profil extends javax.swing.JFrame {

    /**
     * Creates new form profil
     */
    public profil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kos1 = new javax.swing.JButton();
        kos2 = new javax.swing.JButton();
        kos3 = new javax.swing.JButton();
        kos4 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kos1.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        kos1.setText("+");
        kos1.setContentAreaFilled(false);
        kos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kos1ActionPerformed(evt);
            }
        });
        getContentPane().add(kos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 170, 90));

        kos2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        kos2.setText("+");
        kos2.setContentAreaFilled(false);
        kos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kos2ActionPerformed(evt);
            }
        });
        getContentPane().add(kos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 170, 90));

        kos3.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        kos3.setText("+");
        kos3.setContentAreaFilled(false);
        kos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kos3ActionPerformed(evt);
            }
        });
        getContentPane().add(kos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 170, 90));

        kos4.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        kos4.setText("+");
        kos4.setContentAreaFilled(false);
        kos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kos4ActionPerformed(evt);
            }
        });
        getContentPane().add(kos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 170, 90));

        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 53, 70, 30));

        close.setContentAreaFilled(false);
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 0, 30, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tambah.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 810, 600));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 180, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kos1ActionPerformed
    new kos1().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_kos1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    new login().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void kos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kos2ActionPerformed
    new kos1().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_kos2ActionPerformed

    private void kos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kos3ActionPerformed
    new kos1().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_kos3ActionPerformed

    private void kos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kos4ActionPerformed
    new kos1().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_kos4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton close;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kos1;
    private javax.swing.JButton kos2;
    private javax.swing.JButton kos3;
    private javax.swing.JButton kos4;
    // End of variables declaration//GEN-END:variables
}
