

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nanda
 */
public class simpan extends javax.swing.JFrame {
public static String Nama;
public static String kell;
public static String acc;
public static String lengkapp;
    /**
     * Creates new form simpan
     */
    public simpan() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelamin = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        fasilitasumum = new javax.swing.JPanel();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        keteranganlain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        deskripsikost = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        fasilitaskmr = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        fasilitasmnd = new javax.swing.JPanel();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        akseslingkungan = new javax.swing.JPanel();
        warung = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        back = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fasilitasumum.setBackground(new java.awt.Color(204, 204, 255));
        fasilitasumum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fasilitasumum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox22.setText("Ruang Tamu");
        jCheckBox22.setContentAreaFilled(false);
        fasilitasumum.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jCheckBox23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox23.setText("Dapur");
        jCheckBox23.setContentAreaFilled(false);
        fasilitasumum.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jCheckBox24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox24.setText("Kulkas");
        jCheckBox24.setContentAreaFilled(false);
        fasilitasumum.add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jCheckBox25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox25.setText("Ruang Makan");
        jCheckBox25.setContentAreaFilled(false);
        fasilitasumum.add(jCheckBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jCheckBox26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox26.setText("Ruang Santai");
        jCheckBox26.setContentAreaFilled(false);
        fasilitasumum.add(jCheckBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jCheckBox27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox27.setText("Kamar Mandi Luar");
        jCheckBox27.setContentAreaFilled(false);
        fasilitasumum.add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jCheckBox28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox28.setText("TV");
        jCheckBox28.setContentAreaFilled(false);
        jCheckBox28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox28ActionPerformed(evt);
            }
        });
        fasilitasumum.add(jCheckBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jCheckBox29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox29.setText("Ruang Keluarga");
        jCheckBox29.setContentAreaFilled(false);
        fasilitasumum.add(jCheckBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jCheckBox30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox30.setText("Ruang Cuci");
        jCheckBox30.setContentAreaFilled(false);
        fasilitasumum.add(jCheckBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jCheckBox31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox31.setText("Ruang Jemur");
        jCheckBox31.setContentAreaFilled(false);
        fasilitasumum.add(jCheckBox31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jTabbedPane1.addTab("Fasilitas Umum", fasilitasumum);

        keteranganlain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        keteranganlain.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 200));

        jTabbedPane1.addTab("Keterangan Lain", keteranganlain);

        deskripsikost.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        deskripsikost.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 190));

        jTabbedPane1.addTab("Deskripsi Kost", deskripsikost);

        fasilitaskmr.setBackground(new java.awt.Color(204, 204, 255));
        fasilitaskmr.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fasilitaskmr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox1.setText("Kasur");
        jCheckBox1.setContentAreaFilled(false);
        fasilitaskmr.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox2.setText("Lemari");
        jCheckBox2.setContentAreaFilled(false);
        fasilitaskmr.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox3.setText("kipas");
        jCheckBox3.setContentAreaFilled(false);
        fasilitaskmr.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox4.setText("Kulkas");
        jCheckBox4.setContentAreaFilled(false);
        fasilitaskmr.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox5.setText("Selimut");
        jCheckBox5.setContentAreaFilled(false);
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        fasilitaskmr.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox6.setText("Wifi");
        jCheckBox6.setContentAreaFilled(false);
        fasilitaskmr.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox7.setText("Bantal");
        jCheckBox7.setContentAreaFilled(false);
        fasilitaskmr.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox8.setText("Televisi");
        jCheckBox8.setContentAreaFilled(false);
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        fasilitaskmr.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jCheckBox9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox9.setText("Guling");
        jCheckBox9.setContentAreaFilled(false);
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        fasilitaskmr.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jTabbedPane1.addTab("Fasilitas Kamar", fasilitaskmr);

        fasilitasmnd.setBackground(new java.awt.Color(204, 204, 255));
        fasilitasmnd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox10.setText("Gayung");
        jCheckBox10.setContentAreaFilled(false);
        fasilitasmnd.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jCheckBox11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox11.setText("Gantungan");
        jCheckBox11.setContentAreaFilled(false);
        fasilitasmnd.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jCheckBox12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox12.setText("Cermin");
        jCheckBox12.setContentAreaFilled(false);
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        fasilitasmnd.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jCheckBox13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox13.setText("Toilet Duduk");
        jCheckBox13.setContentAreaFilled(false);
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        fasilitasmnd.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jCheckBox14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox14.setText("Toilet Jongkok");
        jCheckBox14.setContentAreaFilled(false);
        fasilitasmnd.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jCheckBox15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox15.setText("Ember");
        jCheckBox15.setContentAreaFilled(false);
        fasilitasmnd.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jTabbedPane1.addTab("Fasilitas Kamar Mandi", fasilitasmnd);

        akseslingkungan.setBackground(new java.awt.Color(204, 204, 255));
        akseslingkungan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warung.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        warung.setText("Warung");
        warung.setContentAreaFilled(false);
        akseslingkungan.add(warung, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jCheckBox17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox17.setText("ATM/Bank");
        jCheckBox17.setContentAreaFilled(false);
        akseslingkungan.add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jCheckBox18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox18.setText("Kampus/Sekolah");
        jCheckBox18.setContentAreaFilled(false);
        akseslingkungan.add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jCheckBox19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox19.setText("Apotek");
        jCheckBox19.setContentAreaFilled(false);
        akseslingkungan.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jCheckBox20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox20.setText("Masjid");
        jCheckBox20.setContentAreaFilled(false);
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });
        akseslingkungan.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jCheckBox21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox21.setText("Mini Market");
        jCheckBox21.setContentAreaFilled(false);
        akseslingkungan.add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jTabbedPane1.addTab("Akses Lingkungan", akseslingkungan);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 540, 240));

        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 50, 30));

        simpan.setContentAreaFilled(false);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 100, 40));

        close.setContentAreaFilled(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 0, 30, 20));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 165, 180, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 189, 180, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 213, 180, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 237, 180, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 180, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/Simpangan.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 830, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    new profil().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
    warung.isSelected();
    new kos1().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_simpanActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
    this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jCheckBox28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox28ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simpan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simpan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simpan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simpan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simpan().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel akseslingkungan;
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton close;
    private javax.swing.JPanel deskripsikost;
    private javax.swing.JPanel fasilitaskmr;
    private javax.swing.JPanel fasilitasmnd;
    private javax.swing.JPanel fasilitasumum;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.ButtonGroup kelamin;
    private javax.swing.JPanel keteranganlain;
    private javax.swing.JButton simpan;
    private javax.swing.JCheckBox warung;
    // End of variables declaration//GEN-END:variables

   
}
